### ISSUE TITLE
some addtion imformation about ros control 

### ISSUE THREAD

**Issue by mrzhuzhe** [mrzhuzhe/Gurren#2]
1.我想问一下您，我看见这个cpp 里面都是关于类的定义，那他的实例化发生在哪里呢？找了几个CPP好像都是类的定义，没找到实例化的地方，main程序也没找到

2.我还看了看cartesian_velocity_controller.cpp 里面的速度控制实现依靠的是PositionJointInterface么，原理是 this->joint_handles_[i].setCommand(this->joint_state_.q(i) + Jnt_Vel_Cmd_(i)***period**.toSec()) 发送到关节位置么

3.
if (!node_handle.getParam(name_space + "/test_value", test_value)) {
ROS_ERROR("Cartesian_Velocity_Controller: Could not read parameter test_value");
return false;
} else {
ROS_INFO_STREAM("test_value: " << test_value);
}
这句话里面 + "/test_value", 是您自定义的一个命名空间么，在哪里能看到他？

**Comment by mrzhuzhe** [comment]
1. 这个类是给 ros_control_controller_spawner 来调用的


调用链路：
（1）首先类名当参数传给launch文件
```
roslaunch ur_gazebo ur5e_bringup.launch controllers:=cartesian_velocity_position_controller 
```
（2）在launch文件内部继续传递
```
// ur5e_bringup.launch 
Gurren/my_test/src/robots/universal_robot/fmauch_universal_robot/ur_gazebo/launch/ur5e_bringup.launch
// 传入这一段
<include file="$(dirname)/inc/ur_control.launch.xml">
    <arg name="controller_config_file" value="$(arg controller_config_file)"/>
    <arg name="controllers" value="$(arg controllers)"/>
    <arg name="gui" value="$(arg gui)"/>
    <arg name="paused" value="$(arg paused)"/>
    <arg name="stopped_controllers" value="$(arg stopped_controllers)"/>
  </include>
</launch>


// 最终传给 ros_control_controller_spawner
<!-- Load and start the controllers listed in the 'controllers' arg. -->
  <node name="ros_control_controller_spawner" pkg="controller_manager" type="spawner"
    args="$(arg controllers)" output="screen" respawn="false" />

```

最终传给 ros_control_controller_spawner 这个ROS内部package来实例化

另外：
ros 的 main 我猜测应该是在 ros core 启动消息队列时调用的
ros core 等的初始化应该是在launch文件里

**Comment by mrzhuzhe** [comment]
2. 是的
```
        // Compute inverse kinematics velocity solver
        //  http://docs.ros.org/en/hydro/api/orocos_kdl/html/classKDL_1_1ChainIkSolverVel.html
        ik_vel_solver_->CartToJnt(this->joint_state_.q, End_Vel_Cmd_, Jnt_Vel_Cmd_);
```
（1）先把 End_Vel_Cmd_ 和 Jnt_Vel_Cmd_ 的相互转换
在这里调用KDL 这个库 把末端的速度指令 End_Vel_Cmd_ 转换成 每个关节的速度指令 Jnt_Vel_Cmd_
（2）然后根据关节速度算关节位置
（3）最后位置发给 positionJointInterface

**Comment by mrzhuzhe** [comment]
3. getParam 是获取的 
```
/Gurren/my_test/src/robots/universal_robot/fmauch_universal_robot/ur_gazebo/config/ur5e_controllers.yaml
```

里对应控制器
```
cartesian_velocity_controller:
  type: cartesian_velocity_controller/CartesianVelocityController
  publish_rate: 125
  test_value: ImTestValue
  root_name: base_link
  tip_name: wrist_3_link
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
```
的初始化参数 test_value: ImTestValue
